# Generated by Django 3.1.2 on 2020-10-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
